module.exports = {
  extends: ["./base"],
  rules: {
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-unsafe-assignment": "off",
    "@typescript-eslint/no-unsafe-member-access": "off",
    "@typescript-eslint/no-unsafe-return": "off",
    "@typescript-eslint/no-unsafe-call": "off",
    "@typescript-eslint/no-misused-promises": "off",
    "@typescript-eslint/restrict-template-expressions": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-unnecessary-type-assertion": "off",
    "@typescript-eslint/no-unused-vars": "off",
    "@typescript-eslint/no-unsafe-argument": "off",
    "@typescript-eslint/await-thenable": "off",
    "@typescript-eslint/no-floating-promises": "off",
    "@typescript-eslint/no-implied-eval": "off",
    "@typescript-eslint/unbound-method": "off",
    "@typescript-eslint/require-await": "off",
    "sonarjs/no-duplicate-string": "off",
    "unicorn/prefer-module": "off",
    "unicorn/no-array-reduce": "off",
    "unicorn/prefer-node-protocol": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/prefer-object-from-entries": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-object-as-default-parameter": "off",
    "unicorn/no-useless-promise-resolve-reject": "off",
    "jest/no-export": "off",
    "jest/valid-title": "off",
    "unicorn/prefer-top-level-await": "off",
    "unicorn/prefer-event-target": "off",
    "unicorn/prefer-logical-operator-over-ternary": "off",
  },
};
