import "dayjs/locale/es";

import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";
import localizedFormat from "dayjs/plugin/localizedFormat";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";

dayjs.extend(customParseFormat);
dayjs.extend(localizedFormat);
dayjs.extend(utc);
dayjs.extend(timezone);

import Decimal from "decimal.js";

Decimal.set({ rounding: Decimal.ROUND_FLOOR });

export * from "./alert";
export * from "./argon";
export * from "./backoff";
export * from "./batch-queue";
export * from "./bigquery";
export * from "./cache";
export * from "./calc";
export * from "./card-pin";
export * from "./combination";
export * from "./concurrent";
export * from "./cron";
export * from "./csv";
export * from "./data";
export * from "./database";
export * from "./delay";
export * from "./encoding";
export * from "./environment";
export * from "./error";
export * from "./ethereum-node";
export * from "./files";
export * from "./format";
export * from "./grafana-loki";
export * from "./http";
export * from "./image";
export * from "./json-schema";
export * from "./knex";
export * from "./lambda";
export * from "./lock";
export * from "./logger";
export * from "./metrics";
export * from "./numbers";
export * from "./objects";
export * from "./opentelemetry";
export * from "./p-memoize";
export * from "./path";
export * from "./phone";
export * from "./process";
export * from "./provider-resolver";
export * from "./qr";
export * from "./queue";
export * from "./random";
export * from "./redis-client";
export * from "./reward";
export * from "./s3";
export * from "./sftp";
export * from "./time";
export * from "./totp";
export * from "./uuid";
export * from "./validate";
export * from "@hapi/boom";
export * from "fastify";
